### ISSUE TITLE
Start actuator on different port

### ISSUE THREAD

**Issue by jmewes** [ksch-workflows/backend#101]

**Comment by jmewes** [comment]
```
management:
  endpoints:
    web:
      cors:
        allowedOrigins: '*'
        allowedMethods: GET
      basePath: /api/actuator
  health:
    diskspace:
      enabled: false

```
